### ISSUE TITLE
Property 'children' is incompatible with index signature TS Error

### ISSUE THREAD

**Issue by richbachman** [wayfair/rainbow-sprinkles#101]
## Description

I'm not sure if this is a bug or not but figured I'd post an issue here. I'm running into a TS error when trying to create a Button component from Box. It only seems to happen if I add `colorProperties` to the `createRainbowSprinkles` function. You can see the CodeSandbox here: https://codesandbox.io/s/musing-antonelli-nh703c?file=/components/Box.css.ts:2421-2464

## Expected Behaviour

I should be able to add `colorProperties` to the  `createRainbowSprinkles` function.

## Actual Behaviour

The TS error is `Property 'children' is incompatible with index signature.` You can see that on Button: https://codesandbox.io/s/musing-antonelli-nh703c?file=/components/Button.tsx

![Screenshot 2023-02-07 at 14 49 10](https://user-images.githubusercontent.com/1350081/217375476-e2250a43-4b96-4fec-9104-b00e6cb38815.png)

## Affected Version

0.15.1

## Steps to Reproduce

I've shared the CodeSandbox. You can remove the TS error by commenting out this line: https://codesandbox.io/s/musing-antonelli-nh703c?file=/components/Box.css.ts:2755-2773

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair/rainbow-sprinkles/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by roginfarrer** [comment]
The bug appears to go away if you add the `shorthands` property to `colorProperties`. Looks to be a bug with the types!

**Comment by richbachman** [comment]
@roginfarrer thanks for taking a look at this so quickly. Sure enough, just adding `shorthands: {}` fixes the issue. When you say a bug with types, would that be on the libraries end or something I'm doing incorrectly?

**Comment by roginfarrer** [comment]
It's a bug within rainbow sprinkles

**Comment by roginfarrer** [comment]
I've looked into this a little bit, but I'm not 100% sure how to solve it 🤔 . Would love some help on this one.

**Comment by roginfarrer** [comment]
I think I may have fixed this issue. @richbachman can you try installing this version and see if it fixes it for you?

```
rainbow-sprinkles@0.0.0-reorder-defineproperties-overload-types-20240102060747
```

**Comment by roginfarrer** [comment]
Went ahead and merged it since I'm pretty confident it fixes the issue in my testing. Will release in a patch shortly.

**Comment by richbachman** [comment]
@roginfarrer Apologies for falling off the radar on this one. Work has been busy and my brain is playing catch up. Thanks for looking into this. I'll take a look.
