### ISSUE TITLE
Properties declared in both `staticProperties` and `dynamicProperties` have inline styles applied

### ISSUE THREAD

**Issue by brandonpittman** [wayfair/rainbow-sprinkles#106]
## Description

I've got a static property of `{full: "100%"}` for `height`. I also have `height: true` to allow for  arbitrary height values. The appearance is correct, but the HTML has unnecessary inline styles applied. (ex: a `$full` design token as a custom property value)

 
<img width="599" alt="CleanShot 2023-02-15 at 13 03 36@2x" src="https://user-images.githubusercontent.com/967145/218929241-59a61965-0b8f-4ac2-8a26-ea1fcf63b4c3.png">

## Expected Behaviour

The inline style declaring `$full` should not be applied.

## Actual Behaviour

The inline style declaring `$full` is applied.

## Affected Version

`0.15.2`

## Steps to Reproduce

1. Create static property of `height: {full: "100%"}`
1. Create dynamic property of `height: true`
1. Use like so `<Box height="$full" />`

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair/rainbow-sprinkles/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by roginfarrer** [comment]
Hmm probably an issue somewhere in here https://github.com/wayfair/rainbow-sprinkles/blob/main/packages/rainbow-sprinkles/src/assignVars.ts

I'll take a look when I can, but feel free to look into it, too!
