### ISSUE TITLE
Getting started examples do not work

### ISSUE THREAD

**Issue by bestow-jd** [wayfair/rainbow-sprinkles#111]
- First, the code sandbox does not work
![image](https://user-images.githubusercontent.com/54546611/219445609-2afc69e0-4416-4bb6-85ba-7060f26cf286.png)
- Second, there's some missing code in the example
```ts
export const rainbowSprinkles(responsiveProperties)
```
should be
```ts
export const rainbowSprinkles = createRainbowSprinkles(responsiveProperties)
```
- Finally, even after fixing that above line, the example code does not work due to TS errors

> <html>TS2345: Argument of type 'ReturnConditionalStatic&lt;{ display: (&quot;flex&quot; | &quot;block&quot; | &quot;inline-block&quot; | &quot;inline-flex&quot;)[]; }, { mobile: {}; tablet: { '@media': string; }; desktop: { '@media': string; }; }&gt; &amp; ReturnConditionalDynamic&lt;...&gt; &amp; ReturnShorthands&lt;...&gt;' is not assignable to parameter of type 'DefinePropertiesReturn'.<br/>Types of property 'config' are incompatible.<br/>Type '{ display: { values: Values&lt;(&quot;flex&quot; | &quot;block&quot; | &quot;inline-block&quot; | &quot;inline-flex&quot;)[], ConditionalMap&lt;{ mobile: {}; tablet: { '@media': string; }; desktop: { '@media': string; }; }&gt;&gt;; staticScale: (&quot;flex&quot; | ... 2 more ... | &quot;inline-flex&quot;)[]; name: &quot;display&quot;; }; } &amp; { ...; } &amp; { ...; }' is not assignable to type 'SprinkleProperties'.<br/>Property 'margin' is incompatible with index signature.<br/>Type '{ dynamic: ConditionalMap&lt;{ mobile: {}; tablet: { '@media': string; }; desktop: { '@media': string; }; }&gt;; dynamicScale: { none: number; small: string; medium: string; large: string; }; name: &quot;margin&quot;; vars: ConditionalMap&lt;...&gt;; }' is not assignable to type 'DynamicProperty | StaticProperty | StaticPropertyArray | StaticDynamicPropertyArray | ... 6 more ... | ShorthandProperty'.<br/>Type '{ dynamic: ConditionalMap&lt;{ mobile: {}; tablet: { '@media': string; }; desktop: { '@media': string; }; }&gt;; dynamicScale: { none: number; small: string; medium: string; large: string; }; name: &quot;margin&quot;; vars: ConditionalMap&lt;...&gt;; }' is missing the following properties from type 'StaticDynamicConditionalProperty': values, staticScale

My package.json:
```
{
  "name": "remix-style-sandbox-c2ed",
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "run-s build:*",
    "build:remix": "remix build",
    "dev": "run-p dev:*",
    "dev:remix": "cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev",
    "format": "prettier --write .",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint .",
    "setup": "prisma generate && prisma migrate deploy && prisma db seed",
    "start": "remix-serve build",
    "start:mocks": "binode --require ./mocks -- @remix-run/serve:remix-serve build",
    "test": "vitest",
    "test:e2e:dev": "start-server-and-test dev http://localhost:3000 \"npx cypress open\"",
    "pretest:e2e:run": "npm run build",
    "test:e2e:run": "cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 \"npx cypress run\"",
    "typecheck": "tsc && tsc -p cypress",
    "validate": "run-p \"test -- --run\" lint typecheck test:e2e:run"
  },
  "prettier": {},
  "eslintIgnore": [
    "/node_modules",
    "/build",
    "/public/build"
  ],
  "dependencies": {
    "@prisma/client": "^4.9.0",
    "@remix-run/css-bundle": "^1.12.0",
    "@remix-run/node": "^1.12.0",
    "@remix-run/react": "^1.12.0",
    "@remix-run/serve": "^1.12.0",
    "@remix-run/server-runtime": "^1.12.0",
    "@vanilla-extract/sprinkles": "^1.5.1",
    "bcryptjs": "^2.4.3",
    "isbot": "^3.6.5",
    "lodash.merge": "^4.6.2",
    "rainbow-sprinkles": "^0.15.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tiny-invariant": "^1.3.1"
  },
  "devDependencies": {
    "@faker-js/faker": "^7.6.0",
    "@remix-run/dev": "^1.12.0",
    "@remix-run/eslint-config": "^1.12.0",
    "@testing-library/cypress": "^8.0.7",
    "@testing-library/dom": "^8.20.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/bcryptjs": "^2.4.2",
    "@types/eslint": "^8.4.10",
    "@types/lodash.merge": "^4.6.7",
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "@vanilla-extract/css": "^1.9.5",
    "@vitejs/plugin-react": "^3.0.1",
    "@vitest/coverage-c8": "^0.27.2",
    "autoprefixer": "^10.4.13",
    "binode": "^1.0.5",
    "c8": "^7.12.0",
    "cookie": "^0.5.0",
    "cross-env": "^7.0.3",
    "cypress": "^10.11.0",
    "eslint": "^8.32.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-cypress": "^2.12.1",
    "happy-dom": "^8.1.4",
    "msw": "^0.49.2",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.21",
    "prettier": "2.8.3",
    "prisma": "^4.9.0",
    "start-server-and-test": "^1.15.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.2",
    "typescript": "^4.9.4",
    "vite": "^4.0.4",
    "vite-tsconfig-paths": "^3.6.0",
    "vitest": "^0.27.2"
  },
  "engines": {
    "node": ">=14"
  },
  "prisma": {
    "seed": "ts-node --require tsconfig-paths/register prisma/seed.ts"
  }
}

```

**Comment by roginfarrer** [comment]
Thanks! Fixed it with a new demo

**Comment by airtonix** [comment]
Nope. example is still brokeded. 

@roginfarrer what "new demo" are you talking about ?
