### ISSUE TITLE
Docs typo: README.md const rainbowSprinkles code snippet missing something

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wayfair/rainbow-sprinkles#148]
## Description

From the README.md:

https://github.com/wayfair/rainbow-sprinkles/blob/e1ed0f189737261edb618c3f0ac2776622d5fc9e/packages/rainbow-sprinkles/README.md?plain=1#L118

I tried changing to `export const rainbowSprinkles = createRainbowSprinkles(responsiveProperties)` but got a TypeScript type error.

What was that supposed to be? 🙂

**Comment by yyyyaaa** [comment]
@JoshuaKGoldberg probably just missing a variable on the left hand side and wrong function name, this should work:
```
export const rainbowSprinkles = createRainbowSprinkles(
  responsiveProperties,
  interactiveProperties
);
```
