### ISSUE TITLE
Allow only shorthands

### ISSUE THREAD

**Issue by olivierpascal** [wayfair/rainbow-sprinkles#175]
## Problem Statement

Sprinkles types include regular properties and shorthands. I would like to allow only shorthands.

## Proposed Solution

-

## Alternatives Considered

-

## Additional Context

-

**Comment by roginfarrer** [comment]
You can do this now by adding an abstraction around the `rainbowSprinkles` function.

```typescript
const rainbowSprinkles = createRainbowSprinkles(/* your sprinkles */)

type Sprinkles = Parameters<typeof rainbowSprinkles>[0];

function onlyShorthands(styles: Pick<Sprinkles, 'your' | 'shorthands'>) {
  // you can optionally filter the styles if you don't want to allow regular properties at runtime/functionally
  return rainbowSprinkles(styles);
}
```

Hope this helps.

**Comment by olivierpascal** [comment]
Thank you for your reply! I would have prefer to do something like this:

```tsx
type SprinklesShorthands = Pick<
  Sprinkles,
  keyof typeof xxx.shorthands
>;
```
