### ISSUE TITLE
staticProperties does not apply styles

### ISSUE THREAD

**Issue by Meemaw** [wayfair/rainbow-sprinkles#99]
## Description
Defining a property in `staticProperties` does not apply styles. For example,

```js
const vars = {
  cursor: {
    pointer: "pointer",
  },
}

const responsiveProperties = defineProperties({
  staticProperties: {
    cursor: vars.cursor,
  },
})
```

Adding this, component that uses this:

```js
import { rainbowSprinkles } from "../sprinkles.css"

export const container = rainbowSprinkles({
  cursor: "pointer",
})
```

will no longer have `cursor: pointer` work properly. If `cursor` property is removed from the `staticProperties`, it works.

**Comment by roginfarrer** [comment]
When you use the object syntax for `staticProperties`, you are opting into using the `$` prefix. This should work:

```diff
export const container = rainbowSprinkles({
-  cursor: "pointer",
+  cursor: "$pointer",
})
```

If you just want to use the value `'pointer'`, you should use the array syntax:

```typescript
const responsiveProperties = defineProperties({
  staticProperties: {
    cursor: ['pointer'],
  },
})
```

Hope that helps!
